name = "cyberwatch-tracker"
main = "worker.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "cyberwatch-tracker-db"
database_id = "REMPLACE_MOI_APRES_CREATION_DB"

[vars]
ALLOWED_ORIGIN = "https://cyberthreatwatch.ca,https://amadouourydiallo2026.github.io"
